name : Hello from git hub CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v2
      - name: Hello World
        run: echo "hello world"
        shell: bash
  good-bye:
    runs-on: unbuntu-latest
    steps:
      - name: good bye world
        run: echo "Good Bye World"
        shell: bash